# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TelemetryPacket.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'TelemetryPacket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15TelemetryPacket.proto\"\xbc\x05\n\x0fTelemetryPacket\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\r\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\r\x12\x1b\n\x05state\x18\x03 \x01(\x0e\x32\x0c.FlightState\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x04 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x05 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x06 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x07 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x08 \x01(\x02\x12\x0e\n\x06gyro_z\x18\t \x01(\x02\x12\x13\n\x0bkf_altitude\x18\n \x01(\x02\x12\x13\n\x0bkf_velocity\x18\x0b \x01(\x02\x12\x17\n\x0fkf_alt_variance\x18\x16 \x01(\x02\x12\x17\n\x0fkf_vel_variance\x18\x17 \x01(\x02\x12\x15\n\rbaro0_healthy\x18\x0c \x01(\x08\x12\x15\n\rbaro1_healthy\x18\r \x01(\x08\x12\x16\n\x0e\x62\x61ro0_pressure\x18\x18 \x01(\x02\x12\x19\n\x11\x62\x61ro0_temperature\x18\x19 \x01(\x02\x12\x16\n\x0e\x62\x61ro0_altitude\x18\x1a \x01(\x02\x12\x11\n\tbaro0_nis\x18\x1b \x01(\x02\x12\x14\n\x0c\x62\x61ro0_faults\x18\x1c \x01(\r\x12\x16\n\x0e\x62\x61ro1_pressure\x18\x1d \x01(\x02\x12\x19\n\x11\x62\x61ro1_temperature\x18\x1e \x01(\x02\x12\x16\n\x0e\x62\x61ro1_altitude\x18\x1f \x01(\x02\x12\x11\n\tbaro1_nis\x18  \x01(\x02\x12\x14\n\x0c\x62\x61ro1_faults\x18! \x01(\r\x12\x17\n\x0fground_altitude\x18\x0e \x01(\x02\x12\x14\n\x0cgps_latitude\x18\x0f \x01(\x02\x12\x15\n\rgps_longitude\x18\x10 \x01(\x02\x12\x14\n\x0cgps_altitude\x18\x11 \x01(\x02\x12\x11\n\tgps_speed\x18\x12 \x01(\x02\x12\x10\n\x08gps_sats\x18\x13 \x01(\r\x12\x0f\n\x07gps_fix\x18\x14 \x01(\r*g\n\x0b\x46lightState\x12\x0b\n\x07STANDBY\x10\x00\x12\n\n\x06\x41SCENT\x10\x01\x12\r\n\tMACH_LOCK\x10\x02\x12\x12\n\x0e\x44ROGUE_DESCENT\x10\x03\x12\x10\n\x0cMAIN_DESCENT\x10\x04\x12\n\n\x06LANDED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TelemetryPacket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLIGHTSTATE']._serialized_start=728
  _globals['_FLIGHTSTATE']._serialized_end=831
  _globals['_TELEMETRYPACKET']._serialized_start=26
  _globals['_TELEMETRYPACKET']._serialized_end=726
# @@protoc_insertion_point(module_scope)
